import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const divStyle = {
    backgroundColor: "red",
  };
  return (
    <html lang="en">
      <body style={divStyle} className={inter.className}>
        {children}
      </body>
    </html>
  );
}
